version: '2'
services:
    myapp-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/MyApp/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=MyApp
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
